In [20]:
import pandas as pd

In [32]:
import mysql.connector

In [33]:
#read the data
police_ledger=pd.read_csv(r"C:\Users\WINDOWS\Downloads\police_file.csv",low_memory=False)

In [34]:
police_ledger

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924

In [35]:
#information
police_ledger.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  object
 1   stop_time           65538 non-null  object
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  object
 7   violation_raw       65538 non-null  object
 8   violation           65538 non-null  object
 9   search_conducted    65538 non-null  bool
 10  search_type         43818 non-null  object
 11  stop_outcome        65538 non-null  object
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  object
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  object
dtypes: bool(3), int64(2), object(11)
memory usage: 6.7+ MB

In [36]:
#check the missing values
police_ledger.isnull().sum()

stop_date                 0
stop_time                 0
country_name              0
driver_gender             0
driver_age_raw            0
driver_age                0
driver_race               0
violation_raw             0
violation                 0
search_conducted          0
search_type           21720
stop_outcome              0
is_arrested               0
stop_duration             0
drugs_related_stop        0
vehicle_number            0
dtype: int64

In [37]:
#fill the Nan values
police_ledger.fillna({'search_type':'None'},inplace=True)
police_ledger.isnull().sum()

stop_date             0
stop_time             0
country_name          0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
vehicle_number        0
dtype: int64

In [38]:
#Drop the columns
police_ledger.drop('driver_age_raw',axis=1)

,stop_date,stop_time,country_name,driver_gender,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,63,Black,Seatbelt,Other,False,None,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,32,Other,Seatbelt,Speeding,True,None,Ticket,True,16-30 Min,False,UP89PT2924

In [39]:
#identify the date&time data type
police_ledger['stop_date']=pd.to_datetime(police_ledger['stop_date'])
police_ledger['stop_time']=pd.to_datetime(police_ledger['stop_time'])

C:\Users\WINDOWS\AppData\Local\Temp\ipykernel_7796\3301965685.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  police_ledger['stop_time']=pd.to_datetime(police_ledger['stop_time'])

In [40]:
police_ledger.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  datetime64[ns]
 1   stop_time           65538 non-null  datetime64[ns]
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  object
 7   violation_raw       65538 non-null  object
 8   violation           65538 non-null  object
 9   search_conducted    65538 non-null  bool
 10  search_type         65538 non-null  object
 11  stop_outcome        65538 non-null  object
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  object
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  object
dtypes: bool(3), datetime64[ns](2), int64(2), object(9)
memory usage: 6.7+ MB

In [70]:
import pandas as pd

In [71]:
import mysql.connector

In [41]:
import pymysql

In [62]:
#connect to mysql
conn = pymysql.connect(
    host="localhost",
    user="root",
    password="root",
)
cursor = conn.cursor()
cursor.execute("create database police_log")

1

In [61]:
cursor.execute("DROP DATABASE IF EXISTS police_log")
print("police_log database deleted successfully(if it existed).")
conn.close()

police_log database deleted successfully(if it existed).

In [63]:
cursor.execute("USE police_log;")

0

In [64]:
cursor.execute("""CREATE TABLE IF NOT EXISTS police_check (
               id INT AUTO_INCREMENT PRIMARY KEY,
               stop_date date,
               stop_time time,
               country_name varchar(100),
               driver_gender varchar(10),
               driver_age int,
               driver_race varchar(50),
               violation_raw varchar(100),
               violation varchar(100),
               search_conducted boolean,
               search_type varchar(100),
               stop_outcome varchar(100),
               is_arrested boolean,
               stop_duration varchar(50),
               drugs_related_stop boolean,
               vehicle_number varchar(50)
)""")

0

In [65]:
#prepare insert query
insert_query = """
INSERT INTO police_check (
stop_date, stop_time, country_name,	driver_gender, driver_age,	driver_race, violation_raw,	violation, search_conducted, search_type, stop_outcome,
is_arrested, stop_duration,	drugs_related_stop,	vehicle_number) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s)
"""

In [72]:
#Using iterrows to insert Rows
for index, row in police_ledger.iterrows():
    cursor.execute(insert_query, ( 
    row['stop_date'],
    row['stop_time'],
    row['country_name'],
    row['driver_gender'],
    row['driver_age'],
    row['driver_race'],
    row['violation_raw'],
    row['violation'],
    row['search_conducted'],
    row['search_type'],
    row['stop_outcome'],
    row['is_arrested'],
    row['stop_duration'],
    row['drugs_related_stop'],
    row['vehicle_number']
))    
conn.commit()
cursor.close()
conn.close()
print("Data inserted successfully using iterrows()!")

Data inserted successfully using iterrows()!